import type { BaseCategory } from "./types.js";

export const BASE_CATEGORIES: readonly BaseCategory[] = [
  {
    id: "base:food",
    emoji: "🍜",
    title: "Food",
    keywords: [
      "lunch",
      "dinner",
      "breakfast",
      "brunch",
      "cafe",
      "coffee",
      "restaurant",
      "takeaway",
      "biryani",
      "pizza",
      "sushi",
      "ramen",
      "burger",
      "snack",
      "bar",
      "drinks",
    ],
  },
  {
    id: "base:transport",
    emoji: "🚕",
    title: "Transport",
    keywords: [
      "grab",
      "gojek",
      "tada",
      "uber",
      "taxi",
      "cab",
      "bus",
      "mrt",
      "metro",
      "train",
      "subway",
      "parking",
      "toll",
      "petrol",
      "gas",
    ],
  },
  {
    id: "base:home",
    emoji: "🏠",
    title: "Home",
    keywords: [
      "rent",
      "mortgage",
      "furniture",
      "ikea",
      "repairs",
      "cleaning",
      "maid",
      "gardening",
    ],
  },
  {
    id: "base:groceries",
    emoji: "🛒",
    title: "Groceries",
    keywords: [
      "ntuc",
      "fairprice",
      "coldstorage",
      "cold storage",
      "market",
      "supermarket",
      "sheng siong",
      "produce",
      "fruit",
      "vegetables",
    ],
  },
  {
    id: "base:entertainment",
    emoji: "🎉",
    title: "Entertainment",
    keywords: [
      "movie",
      "cinema",
      "concert",
      "netflix",
      "spotify",
      "ktv",
      "club",
      "tickets",
      "show",
      "game",
    ],
  },
  {
    id: "base:travel",
    emoji: "✈️",
    title: "Travel",
    keywords: [
      "flight",
      "airbnb",
      "hotel",
      "hostel",
      "booking",
      "trip",
      "vacation",
      "bali",
      "japan",
      "thailand",
    ],
  },
  {
    id: "base:health",
    emoji: "💊",
    title: "Health",
    keywords: [
      "doctor",
      "clinic",
      "hospital",
      "pharmacy",
      "medicine",
      "gym",
      "massage",
      "dentist",
    ],
  },
  {
    id: "base:shopping",
    emoji: "🛍️",
    title: "Shopping",
    keywords: [
      "clothes",
      "shoes",
      "electronics",
      "lazada",
      "shopee",
      "amazon",
      "gift",
      "souvenir",
    ],
  },
  {
    id: "base:utilities",
    emoji: "💡",
    title: "Utilities",
    keywords: [
      "electricity",
      "water",
      "internet",
      "wifi",
      "phone bill",
      "mobile",
      "starhub",
      "singtel",
      "m1",
    ],
  },
  {
    id: "base:other",
    emoji: "📦",
    title: "Other",
    keywords: [
      "misc",
      "other",
      "general",
      "insurance",
      "fees",
      "subscription",
      "donation",
      "charity",
    ],
  },
];
