/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TmaRouteImport } from './routes/_tma'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TmaHomeRouteImport } from './routes/_tma/home'
import { Route as TmaChatRouteImport } from './routes/_tma/chat'
import { Route as TmaChatIndexRouteImport } from './routes/_tma/chat.index'
import { Route as TmaChatChatIdRouteImport } from './routes/_tma/chat.$chatId'
import { Route as TmaChatChatIdSnapshotsRouteImport } from './routes/_tma/chat.$chatId_.snapshots'
import { Route as TmaChatChatIdSettingsRouteImport } from './routes/_tma/chat.$chatId_.settings'
import { Route as TmaChatChatIdRecurringExpensesRouteImport } from './routes/_tma/chat.$chatId_.recurring-expenses'
import { Route as TmaChatChatIdCreateSnapshotRouteImport } from './routes/_tma/chat.$chatId_.create-snapshot'
import { Route as TmaChatChatIdAddExpenseRouteImport } from './routes/_tma/chat.$chatId_.add-expense'
import { Route as TmaChatChatIdSettingsIndexRouteImport } from './routes/_tma/chat.$chatId_.settings.index'
import { Route as TmaChatChatIdSnapshotsSnapshotIdRouteImport } from './routes/_tma/chat.$chatId_.snapshots_.$snapshotId'
import { Route as TmaChatChatIdSettingsMembersRouteImport } from './routes/_tma/chat.$chatId_.settings.members'
import { Route as TmaChatChatIdSettingsCurrencyRouteImport } from './routes/_tma/chat.$chatId_.settings.currency'
import { Route as TmaChatChatIdSettingsCategoriesRouteImport } from './routes/_tma/chat.$chatId_.settings.categories'
import { Route as TmaChatChatIdEditSnapshotSnapshotIdRouteImport } from './routes/_tma/chat.$chatId_.edit-snapshot.$snapshotId'
import { Route as TmaChatChatIdEditRecurringTemplateIdRouteImport } from './routes/_tma/chat.$chatId_.edit-recurring.$templateId'
import { Route as TmaChatChatIdEditExpenseExpenseIdRouteImport } from './routes/_tma/chat.$chatId_.edit-expense.$expenseId'
import { Route as TmaChatChatIdSettingsCategoriesIndexRouteImport } from './routes/_tma/chat.$chatId_.settings.categories.index'
import { Route as TmaChatChatIdSettingsCategoriesOrganizeRouteImport } from './routes/_tma/chat.$chatId_.settings.categories.organize'
import { Route as TmaChatChatIdSettingsCategoriesNewRouteImport } from './routes/_tma/chat.$chatId_.settings.categories.new'
import { Route as TmaChatChatIdSettingsCategoriesCategoryIdRouteImport } from './routes/_tma/chat.$chatId_.settings.categories.$categoryId'

const TmaRoute = TmaRouteImport.update({
  id: '/_tma',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TmaHomeRoute = TmaHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => TmaRoute,
} as any)
const TmaChatRoute = TmaChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => TmaRoute,
} as any)
const TmaChatIndexRoute = TmaChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TmaChatRoute,
} as any)
const TmaChatChatIdRoute = TmaChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => TmaChatRoute,
} as any)
const TmaChatChatIdSnapshotsRoute = TmaChatChatIdSnapshotsRouteImport.update({
  id: '/$chatId_/snapshots',
  path: '/$chatId/snapshots',
  getParentRoute: () => TmaChatRoute,
} as any)
const TmaChatChatIdSettingsRoute = TmaChatChatIdSettingsRouteImport.update({
  id: '/$chatId_/settings',
  path: '/$chatId/settings',
  getParentRoute: () => TmaChatRoute,
} as any)
const TmaChatChatIdRecurringExpensesRoute =
  TmaChatChatIdRecurringExpensesRouteImport.update({
    id: '/$chatId_/recurring-expenses',
    path: '/$chatId/recurring-expenses',
    getParentRoute: () => TmaChatRoute,
  } as any)
const TmaChatChatIdCreateSnapshotRoute =
  TmaChatChatIdCreateSnapshotRouteImport.update({
    id: '/$chatId_/create-snapshot',
    path: '/$chatId/create-snapshot',
    getParentRoute: () => TmaChatRoute,
  } as any)
const TmaChatChatIdAddExpenseRoute = TmaChatChatIdAddExpenseRouteImport.update({
  id: '/$chatId_/add-expense',
  path: '/$chatId/add-expense',
  getParentRoute: () => TmaChatRoute,
} as any)
const TmaChatChatIdSettingsIndexRoute =
  TmaChatChatIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TmaChatChatIdSettingsRoute,
  } as any)
const TmaChatChatIdSnapshotsSnapshotIdRoute =
  TmaChatChatIdSnapshotsSnapshotIdRouteImport.update({
    id: '/$chatId_/snapshots_/$snapshotId',
    path: '/$chatId/snapshots/$snapshotId',
    getParentRoute: () => TmaChatRoute,
  } as any)
const TmaChatChatIdSettingsMembersRoute =
  TmaChatChatIdSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => TmaChatChatIdSettingsRoute,
  } as any)
const TmaChatChatIdSettingsCurrencyRoute =
  TmaChatChatIdSettingsCurrencyRouteImport.update({
    id: '/currency',
    path: '/currency',
    getParentRoute: () => TmaChatChatIdSettingsRoute,
  } as any)
const TmaChatChatIdSettingsCategoriesRoute =
  TmaChatChatIdSettingsCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => TmaChatChatIdSettingsRoute,
  } as any)
const TmaChatChatIdEditSnapshotSnapshotIdRoute =
  TmaChatChatIdEditSnapshotSnapshotIdRouteImport.update({
    id: '/$chatId_/edit-snapshot/$snapshotId',
    path: '/$chatId/edit-snapshot/$snapshotId',
    getParentRoute: () => TmaChatRoute,
  } as any)
const TmaChatChatIdEditRecurringTemplateIdRoute =
  TmaChatChatIdEditRecurringTemplateIdRouteImport.update({
    id: '/$chatId_/edit-recurring/$templateId',
    path: '/$chatId/edit-recurring/$templateId',
    getParentRoute: () => TmaChatRoute,
  } as any)
const TmaChatChatIdEditExpenseExpenseIdRoute =
  TmaChatChatIdEditExpenseExpenseIdRouteImport.update({
    id: '/$chatId_/edit-expense/$expenseId',
    path: '/$chatId/edit-expense/$expenseId',
    getParentRoute: () => TmaChatRoute,
  } as any)
const TmaChatChatIdSettingsCategoriesIndexRoute =
  TmaChatChatIdSettingsCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TmaChatChatIdSettingsCategoriesRoute,
  } as any)
const TmaChatChatIdSettingsCategoriesOrganizeRoute =
  TmaChatChatIdSettingsCategoriesOrganizeRouteImport.update({
    id: '/organize',
    path: '/organize',
    getParentRoute: () => TmaChatChatIdSettingsCategoriesRoute,
  } as any)
const TmaChatChatIdSettingsCategoriesNewRoute =
  TmaChatChatIdSettingsCategoriesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => TmaChatChatIdSettingsCategoriesRoute,
  } as any)
const TmaChatChatIdSettingsCategoriesCategoryIdRoute =
  TmaChatChatIdSettingsCategoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => TmaChatChatIdSettingsCategoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof TmaChatRouteWithChildren
  '/home': typeof TmaHomeRoute
  '/chat/$chatId': typeof TmaChatChatIdRoute
  '/chat/': typeof TmaChatIndexRoute
  '/chat/$chatId/add-expense': typeof TmaChatChatIdAddExpenseRoute
  '/chat/$chatId/create-snapshot': typeof TmaChatChatIdCreateSnapshotRoute
  '/chat/$chatId/recurring-expenses': typeof TmaChatChatIdRecurringExpensesRoute
  '/chat/$chatId/settings': typeof TmaChatChatIdSettingsRouteWithChildren
  '/chat/$chatId/snapshots': typeof TmaChatChatIdSnapshotsRoute
  '/chat/$chatId/edit-expense/$expenseId': typeof TmaChatChatIdEditExpenseExpenseIdRoute
  '/chat/$chatId/edit-recurring/$templateId': typeof TmaChatChatIdEditRecurringTemplateIdRoute
  '/chat/$chatId/edit-snapshot/$snapshotId': typeof TmaChatChatIdEditSnapshotSnapshotIdRoute
  '/chat/$chatId/settings/categories': typeof TmaChatChatIdSettingsCategoriesRouteWithChildren
  '/chat/$chatId/settings/currency': typeof TmaChatChatIdSettingsCurrencyRoute
  '/chat/$chatId/settings/members': typeof TmaChatChatIdSettingsMembersRoute
  '/chat/$chatId/snapshots/$snapshotId': typeof TmaChatChatIdSnapshotsSnapshotIdRoute
  '/chat/$chatId/settings/': typeof TmaChatChatIdSettingsIndexRoute
  '/chat/$chatId/settings/categories/$categoryId': typeof TmaChatChatIdSettingsCategoriesCategoryIdRoute
  '/chat/$chatId/settings/categories/new': typeof TmaChatChatIdSettingsCategoriesNewRoute
  '/chat/$chatId/settings/categories/organize': typeof TmaChatChatIdSettingsCategoriesOrganizeRoute
  '/chat/$chatId/settings/categories/': typeof TmaChatChatIdSettingsCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof TmaHomeRoute
  '/chat/$chatId': typeof TmaChatChatIdRoute
  '/chat': typeof TmaChatIndexRoute
  '/chat/$chatId/add-expense': typeof TmaChatChatIdAddExpenseRoute
  '/chat/$chatId/create-snapshot': typeof TmaChatChatIdCreateSnapshotRoute
  '/chat/$chatId/recurring-expenses': typeof TmaChatChatIdRecurringExpensesRoute
  '/chat/$chatId/snapshots': typeof TmaChatChatIdSnapshotsRoute
  '/chat/$chatId/edit-expense/$expenseId': typeof TmaChatChatIdEditExpenseExpenseIdRoute
  '/chat/$chatId/edit-recurring/$templateId': typeof TmaChatChatIdEditRecurringTemplateIdRoute
  '/chat/$chatId/edit-snapshot/$snapshotId': typeof TmaChatChatIdEditSnapshotSnapshotIdRoute
  '/chat/$chatId/settings/currency': typeof TmaChatChatIdSettingsCurrencyRoute
  '/chat/$chatId/settings/members': typeof TmaChatChatIdSettingsMembersRoute
  '/chat/$chatId/snapshots/$snapshotId': typeof TmaChatChatIdSnapshotsSnapshotIdRoute
  '/chat/$chatId/settings': typeof TmaChatChatIdSettingsIndexRoute
  '/chat/$chatId/settings/categories/$categoryId': typeof TmaChatChatIdSettingsCategoriesCategoryIdRoute
  '/chat/$chatId/settings/categories/new': typeof TmaChatChatIdSettingsCategoriesNewRoute
  '/chat/$chatId/settings/categories/organize': typeof TmaChatChatIdSettingsCategoriesOrganizeRoute
  '/chat/$chatId/settings/categories': typeof TmaChatChatIdSettingsCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tma': typeof TmaRouteWithChildren
  '/_tma/chat': typeof TmaChatRouteWithChildren
  '/_tma/home': typeof TmaHomeRoute
  '/_tma/chat/$chatId': typeof TmaChatChatIdRoute
  '/_tma/chat/': typeof TmaChatIndexRoute
  '/_tma/chat/$chatId_/add-expense': typeof TmaChatChatIdAddExpenseRoute
  '/_tma/chat/$chatId_/create-snapshot': typeof TmaChatChatIdCreateSnapshotRoute
  '/_tma/chat/$chatId_/recurring-expenses': typeof TmaChatChatIdRecurringExpensesRoute
  '/_tma/chat/$chatId_/settings': typeof TmaChatChatIdSettingsRouteWithChildren
  '/_tma/chat/$chatId_/snapshots': typeof TmaChatChatIdSnapshotsRoute
  '/_tma/chat/$chatId_/edit-expense/$expenseId': typeof TmaChatChatIdEditExpenseExpenseIdRoute
  '/_tma/chat/$chatId_/edit-recurring/$templateId': typeof TmaChatChatIdEditRecurringTemplateIdRoute
  '/_tma/chat/$chatId_/edit-snapshot/$snapshotId': typeof TmaChatChatIdEditSnapshotSnapshotIdRoute
  '/_tma/chat/$chatId_/settings/categories': typeof TmaChatChatIdSettingsCategoriesRouteWithChildren
  '/_tma/chat/$chatId_/settings/currency': typeof TmaChatChatIdSettingsCurrencyRoute
  '/_tma/chat/$chatId_/settings/members': typeof TmaChatChatIdSettingsMembersRoute
  '/_tma/chat/$chatId_/snapshots_/$snapshotId': typeof TmaChatChatIdSnapshotsSnapshotIdRoute
  '/_tma/chat/$chatId_/settings/': typeof TmaChatChatIdSettingsIndexRoute
  '/_tma/chat/$chatId_/settings/categories/$categoryId': typeof TmaChatChatIdSettingsCategoriesCategoryIdRoute
  '/_tma/chat/$chatId_/settings/categories/new': typeof TmaChatChatIdSettingsCategoriesNewRoute
  '/_tma/chat/$chatId_/settings/categories/organize': typeof TmaChatChatIdSettingsCategoriesOrganizeRoute
  '/_tma/chat/$chatId_/settings/categories/': typeof TmaChatChatIdSettingsCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/home'
    | '/chat/$chatId'
    | '/chat/'
    | '/chat/$chatId/add-expense'
    | '/chat/$chatId/create-snapshot'
    | '/chat/$chatId/recurring-expenses'
    | '/chat/$chatId/settings'
    | '/chat/$chatId/snapshots'
    | '/chat/$chatId/edit-expense/$expenseId'
    | '/chat/$chatId/edit-recurring/$templateId'
    | '/chat/$chatId/edit-snapshot/$snapshotId'
    | '/chat/$chatId/settings/categories'
    | '/chat/$chatId/settings/currency'
    | '/chat/$chatId/settings/members'
    | '/chat/$chatId/snapshots/$snapshotId'
    | '/chat/$chatId/settings/'
    | '/chat/$chatId/settings/categories/$categoryId'
    | '/chat/$chatId/settings/categories/new'
    | '/chat/$chatId/settings/categories/organize'
    | '/chat/$chatId/settings/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/chat/$chatId'
    | '/chat'
    | '/chat/$chatId/add-expense'
    | '/chat/$chatId/create-snapshot'
    | '/chat/$chatId/recurring-expenses'
    | '/chat/$chatId/snapshots'
    | '/chat/$chatId/edit-expense/$expenseId'
    | '/chat/$chatId/edit-recurring/$templateId'
    | '/chat/$chatId/edit-snapshot/$snapshotId'
    | '/chat/$chatId/settings/currency'
    | '/chat/$chatId/settings/members'
    | '/chat/$chatId/snapshots/$snapshotId'
    | '/chat/$chatId/settings'
    | '/chat/$chatId/settings/categories/$categoryId'
    | '/chat/$chatId/settings/categories/new'
    | '/chat/$chatId/settings/categories/organize'
    | '/chat/$chatId/settings/categories'
  id:
    | '__root__'
    | '/'
    | '/_tma'
    | '/_tma/chat'
    | '/_tma/home'
    | '/_tma/chat/$chatId'
    | '/_tma/chat/'
    | '/_tma/chat/$chatId_/add-expense'
    | '/_tma/chat/$chatId_/create-snapshot'
    | '/_tma/chat/$chatId_/recurring-expenses'
    | '/_tma/chat/$chatId_/settings'
    | '/_tma/chat/$chatId_/snapshots'
    | '/_tma/chat/$chatId_/edit-expense/$expenseId'
    | '/_tma/chat/$chatId_/edit-recurring/$templateId'
    | '/_tma/chat/$chatId_/edit-snapshot/$snapshotId'
    | '/_tma/chat/$chatId_/settings/categories'
    | '/_tma/chat/$chatId_/settings/currency'
    | '/_tma/chat/$chatId_/settings/members'
    | '/_tma/chat/$chatId_/snapshots_/$snapshotId'
    | '/_tma/chat/$chatId_/settings/'
    | '/_tma/chat/$chatId_/settings/categories/$categoryId'
    | '/_tma/chat/$chatId_/settings/categories/new'
    | '/_tma/chat/$chatId_/settings/categories/organize'
    | '/_tma/chat/$chatId_/settings/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TmaRoute: typeof TmaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tma': {
      id: '/_tma'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tma/home': {
      id: '/_tma/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof TmaHomeRouteImport
      parentRoute: typeof TmaRoute
    }
    '/_tma/chat': {
      id: '/_tma/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof TmaChatRouteImport
      parentRoute: typeof TmaRoute
    }
    '/_tma/chat/': {
      id: '/_tma/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof TmaChatIndexRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId': {
      id: '/_tma/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof TmaChatChatIdRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId_/snapshots': {
      id: '/_tma/chat/$chatId_/snapshots'
      path: '/$chatId/snapshots'
      fullPath: '/chat/$chatId/snapshots'
      preLoaderRoute: typeof TmaChatChatIdSnapshotsRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId_/settings': {
      id: '/_tma/chat/$chatId_/settings'
      path: '/$chatId/settings'
      fullPath: '/chat/$chatId/settings'
      preLoaderRoute: typeof TmaChatChatIdSettingsRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId_/recurring-expenses': {
      id: '/_tma/chat/$chatId_/recurring-expenses'
      path: '/$chatId/recurring-expenses'
      fullPath: '/chat/$chatId/recurring-expenses'
      preLoaderRoute: typeof TmaChatChatIdRecurringExpensesRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId_/create-snapshot': {
      id: '/_tma/chat/$chatId_/create-snapshot'
      path: '/$chatId/create-snapshot'
      fullPath: '/chat/$chatId/create-snapshot'
      preLoaderRoute: typeof TmaChatChatIdCreateSnapshotRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId_/add-expense': {
      id: '/_tma/chat/$chatId_/add-expense'
      path: '/$chatId/add-expense'
      fullPath: '/chat/$chatId/add-expense'
      preLoaderRoute: typeof TmaChatChatIdAddExpenseRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId_/settings/': {
      id: '/_tma/chat/$chatId_/settings/'
      path: '/'
      fullPath: '/chat/$chatId/settings/'
      preLoaderRoute: typeof TmaChatChatIdSettingsIndexRouteImport
      parentRoute: typeof TmaChatChatIdSettingsRoute
    }
    '/_tma/chat/$chatId_/snapshots_/$snapshotId': {
      id: '/_tma/chat/$chatId_/snapshots_/$snapshotId'
      path: '/$chatId/snapshots/$snapshotId'
      fullPath: '/chat/$chatId/snapshots/$snapshotId'
      preLoaderRoute: typeof TmaChatChatIdSnapshotsSnapshotIdRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId_/settings/members': {
      id: '/_tma/chat/$chatId_/settings/members'
      path: '/members'
      fullPath: '/chat/$chatId/settings/members'
      preLoaderRoute: typeof TmaChatChatIdSettingsMembersRouteImport
      parentRoute: typeof TmaChatChatIdSettingsRoute
    }
    '/_tma/chat/$chatId_/settings/currency': {
      id: '/_tma/chat/$chatId_/settings/currency'
      path: '/currency'
      fullPath: '/chat/$chatId/settings/currency'
      preLoaderRoute: typeof TmaChatChatIdSettingsCurrencyRouteImport
      parentRoute: typeof TmaChatChatIdSettingsRoute
    }
    '/_tma/chat/$chatId_/settings/categories': {
      id: '/_tma/chat/$chatId_/settings/categories'
      path: '/categories'
      fullPath: '/chat/$chatId/settings/categories'
      preLoaderRoute: typeof TmaChatChatIdSettingsCategoriesRouteImport
      parentRoute: typeof TmaChatChatIdSettingsRoute
    }
    '/_tma/chat/$chatId_/edit-snapshot/$snapshotId': {
      id: '/_tma/chat/$chatId_/edit-snapshot/$snapshotId'
      path: '/$chatId/edit-snapshot/$snapshotId'
      fullPath: '/chat/$chatId/edit-snapshot/$snapshotId'
      preLoaderRoute: typeof TmaChatChatIdEditSnapshotSnapshotIdRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId_/edit-recurring/$templateId': {
      id: '/_tma/chat/$chatId_/edit-recurring/$templateId'
      path: '/$chatId/edit-recurring/$templateId'
      fullPath: '/chat/$chatId/edit-recurring/$templateId'
      preLoaderRoute: typeof TmaChatChatIdEditRecurringTemplateIdRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId_/edit-expense/$expenseId': {
      id: '/_tma/chat/$chatId_/edit-expense/$expenseId'
      path: '/$chatId/edit-expense/$expenseId'
      fullPath: '/chat/$chatId/edit-expense/$expenseId'
      preLoaderRoute: typeof TmaChatChatIdEditExpenseExpenseIdRouteImport
      parentRoute: typeof TmaChatRoute
    }
    '/_tma/chat/$chatId_/settings/categories/': {
      id: '/_tma/chat/$chatId_/settings/categories/'
      path: '/'
      fullPath: '/chat/$chatId/settings/categories/'
      preLoaderRoute: typeof TmaChatChatIdSettingsCategoriesIndexRouteImport
      parentRoute: typeof TmaChatChatIdSettingsCategoriesRoute
    }
    '/_tma/chat/$chatId_/settings/categories/organize': {
      id: '/_tma/chat/$chatId_/settings/categories/organize'
      path: '/organize'
      fullPath: '/chat/$chatId/settings/categories/organize'
      preLoaderRoute: typeof TmaChatChatIdSettingsCategoriesOrganizeRouteImport
      parentRoute: typeof TmaChatChatIdSettingsCategoriesRoute
    }
    '/_tma/chat/$chatId_/settings/categories/new': {
      id: '/_tma/chat/$chatId_/settings/categories/new'
      path: '/new'
      fullPath: '/chat/$chatId/settings/categories/new'
      preLoaderRoute: typeof TmaChatChatIdSettingsCategoriesNewRouteImport
      parentRoute: typeof TmaChatChatIdSettingsCategoriesRoute
    }
    '/_tma/chat/$chatId_/settings/categories/$categoryId': {
      id: '/_tma/chat/$chatId_/settings/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/chat/$chatId/settings/categories/$categoryId'
      preLoaderRoute: typeof TmaChatChatIdSettingsCategoriesCategoryIdRouteImport
      parentRoute: typeof TmaChatChatIdSettingsCategoriesRoute
    }
  }
}

interface TmaChatChatIdSettingsCategoriesRouteChildren {
  TmaChatChatIdSettingsCategoriesCategoryIdRoute: typeof TmaChatChatIdSettingsCategoriesCategoryIdRoute
  TmaChatChatIdSettingsCategoriesNewRoute: typeof TmaChatChatIdSettingsCategoriesNewRoute
  TmaChatChatIdSettingsCategoriesOrganizeRoute: typeof TmaChatChatIdSettingsCategoriesOrganizeRoute
  TmaChatChatIdSettingsCategoriesIndexRoute: typeof TmaChatChatIdSettingsCategoriesIndexRoute
}

const TmaChatChatIdSettingsCategoriesRouteChildren: TmaChatChatIdSettingsCategoriesRouteChildren =
  {
    TmaChatChatIdSettingsCategoriesCategoryIdRoute:
      TmaChatChatIdSettingsCategoriesCategoryIdRoute,
    TmaChatChatIdSettingsCategoriesNewRoute:
      TmaChatChatIdSettingsCategoriesNewRoute,
    TmaChatChatIdSettingsCategoriesOrganizeRoute:
      TmaChatChatIdSettingsCategoriesOrganizeRoute,
    TmaChatChatIdSettingsCategoriesIndexRoute:
      TmaChatChatIdSettingsCategoriesIndexRoute,
  }

const TmaChatChatIdSettingsCategoriesRouteWithChildren =
  TmaChatChatIdSettingsCategoriesRoute._addFileChildren(
    TmaChatChatIdSettingsCategoriesRouteChildren,
  )

interface TmaChatChatIdSettingsRouteChildren {
  TmaChatChatIdSettingsCategoriesRoute: typeof TmaChatChatIdSettingsCategoriesRouteWithChildren
  TmaChatChatIdSettingsCurrencyRoute: typeof TmaChatChatIdSettingsCurrencyRoute
  TmaChatChatIdSettingsMembersRoute: typeof TmaChatChatIdSettingsMembersRoute
  TmaChatChatIdSettingsIndexRoute: typeof TmaChatChatIdSettingsIndexRoute
}

const TmaChatChatIdSettingsRouteChildren: TmaChatChatIdSettingsRouteChildren = {
  TmaChatChatIdSettingsCategoriesRoute:
    TmaChatChatIdSettingsCategoriesRouteWithChildren,
  TmaChatChatIdSettingsCurrencyRoute: TmaChatChatIdSettingsCurrencyRoute,
  TmaChatChatIdSettingsMembersRoute: TmaChatChatIdSettingsMembersRoute,
  TmaChatChatIdSettingsIndexRoute: TmaChatChatIdSettingsIndexRoute,
}

const TmaChatChatIdSettingsRouteWithChildren =
  TmaChatChatIdSettingsRoute._addFileChildren(
    TmaChatChatIdSettingsRouteChildren,
  )

interface TmaChatRouteChildren {
  TmaChatChatIdRoute: typeof TmaChatChatIdRoute
  TmaChatIndexRoute: typeof TmaChatIndexRoute
  TmaChatChatIdAddExpenseRoute: typeof TmaChatChatIdAddExpenseRoute
  TmaChatChatIdCreateSnapshotRoute: typeof TmaChatChatIdCreateSnapshotRoute
  TmaChatChatIdRecurringExpensesRoute: typeof TmaChatChatIdRecurringExpensesRoute
  TmaChatChatIdSettingsRoute: typeof TmaChatChatIdSettingsRouteWithChildren
  TmaChatChatIdSnapshotsRoute: typeof TmaChatChatIdSnapshotsRoute
  TmaChatChatIdEditExpenseExpenseIdRoute: typeof TmaChatChatIdEditExpenseExpenseIdRoute
  TmaChatChatIdEditRecurringTemplateIdRoute: typeof TmaChatChatIdEditRecurringTemplateIdRoute
  TmaChatChatIdEditSnapshotSnapshotIdRoute: typeof TmaChatChatIdEditSnapshotSnapshotIdRoute
  TmaChatChatIdSnapshotsSnapshotIdRoute: typeof TmaChatChatIdSnapshotsSnapshotIdRoute
}

const TmaChatRouteChildren: TmaChatRouteChildren = {
  TmaChatChatIdRoute: TmaChatChatIdRoute,
  TmaChatIndexRoute: TmaChatIndexRoute,
  TmaChatChatIdAddExpenseRoute: TmaChatChatIdAddExpenseRoute,
  TmaChatChatIdCreateSnapshotRoute: TmaChatChatIdCreateSnapshotRoute,
  TmaChatChatIdRecurringExpensesRoute: TmaChatChatIdRecurringExpensesRoute,
  TmaChatChatIdSettingsRoute: TmaChatChatIdSettingsRouteWithChildren,
  TmaChatChatIdSnapshotsRoute: TmaChatChatIdSnapshotsRoute,
  TmaChatChatIdEditExpenseExpenseIdRoute:
    TmaChatChatIdEditExpenseExpenseIdRoute,
  TmaChatChatIdEditRecurringTemplateIdRoute:
    TmaChatChatIdEditRecurringTemplateIdRoute,
  TmaChatChatIdEditSnapshotSnapshotIdRoute:
    TmaChatChatIdEditSnapshotSnapshotIdRoute,
  TmaChatChatIdSnapshotsSnapshotIdRoute: TmaChatChatIdSnapshotsSnapshotIdRoute,
}

const TmaChatRouteWithChildren =
  TmaChatRoute._addFileChildren(TmaChatRouteChildren)

interface TmaRouteChildren {
  TmaChatRoute: typeof TmaChatRouteWithChildren
  TmaHomeRoute: typeof TmaHomeRoute
}

const TmaRouteChildren: TmaRouteChildren = {
  TmaChatRoute: TmaChatRouteWithChildren,
  TmaHomeRoute: TmaHomeRoute,
}

const TmaRouteWithChildren = TmaRoute._addFileChildren(TmaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TmaRoute: TmaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
