import { Marked } from "marked";

function escapeHtml(text: string): string {
  if (!text) return "";
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

const telegramHtmlRenderer = {
  heading(this: any, token: any) {
    return `<b>${this.parser.parseInline(token.tokens)}</b>\n\n`;
  },
  paragraph(this: any, token: any) {
    return `${this.parser.parseInline(token.tokens)}\n\n`;
  },
  strong(this: any, token: any) {
    return `<b>${this.parser.parseInline(token.tokens)}</b>`;
  },
  em(this: any, token: any) {
    return `<i>${this.parser.parseInline(token.tokens)}</i>`;
  },
  del(this: any, token: any) {
    return `<s>${this.parser.parseInline(token.tokens)}</s>`;
  },
  link(this: any, token: any) {
    return `<a href="${escapeHtml(token.href)}">${this.parser.parseInline(
      token.tokens
    )}</a>`;
  },
  blockquote(this: any, token: any) {
    return `<i>${this.parser.parseInline(token.tokens)}</i>\n\n`;
  },
  list(this: any, token: any) {
    return `${token.items.map((i: any) => this.listitem(i)).join("")}\n`;
  },
  listitem(this: any, token: any) {
    return `• ${this.parser.parseInline(token.tokens)}\n`;
  },
  br() {
    return `\n`;
  },
  hr() {
    return `\n\n`;
  },
  codespan(token: any) {
    return `<code>${escapeHtml(token.text)}</code>`;
  },
  code(token: any) {
    return `<pre><code>${escapeHtml(token.text)}</code></pre>\n\n`;
  },
  table(token: any) {
    const headerCols = token.header.map((c: any) => c.text);
    const bodyRows = token.rows.map((r: any) => r.map((c: any) => c.text));

    const colWidths = headerCols.map((c: string, i: number) =>
      Math.max(c.length, ...bodyRows.map((r: string[]) => r[i]?.length || 0))
    );

    const headerStr = headerCols
      .map((c: string, i: number) => c.padEnd(colWidths[i]))
      .join(" | ");
    const separatorStr = colWidths
      .map((w: number) => "-".repeat(w))
      .join("-|-");
    const bodyStr = bodyRows
      .map((row: string[]) =>
        row.map((c: string, i: number) => c.padEnd(colWidths[i])).join(" | ")
      )
      .join("\n");

    return `<pre><code>${escapeHtml(headerStr)}\n${separatorStr}\n${escapeHtml(
      bodyStr
    )}</code></pre>\n\n`;
  },
  html(token: any) {
    return escapeHtml(token.text);
  },
  text(token: any) {
    return escapeHtml(token.text);
  },
};

// Use type assertion to avoid `this.parser` missing type errors during build
const configuredMarked = new Marked({ renderer: telegramHtmlRenderer as any });

/**
 * Renders Markdown securely to Telegram's HTML format.
 * This inherently bypasses all MarkdownV2 escaping nightmares by rendering valid HTML!
 */
export function renderTelegramHtml(markdownText: string): string {
  // Parse synchronous, trim trailing double newlines generated by paragraph tags
  return (configuredMarked.parse(markdownText) as string).trim();
}
